Reproducibility
INM-6/multi-area-model pull request #57
Opened 2024-01-17 19:12 UTC by mlober

This PR aims to improve reproducibility by setting the default parameters to those used to produce the dynamics of the metastable state in Schmidt et al. (2018). It also removes redundancies such as the stabilization matrix K_stable.npy and unused parameters in default_parameters.py. 

In the README and code one now finds a small description on how to run the model in the ground and metastable state. This might need refining. 

In addition, it adds a missing object "structure_revered" to the model class that is needed for analysis.

2024-01-19 11:59 UTC, albada commented
All of it looks good to me. I just think the new initial mean membrane potential and the newly introduced structure_reversed require a little bit of documentation describing the reasoning behind these.

2024-01-20 15:02 UTC, didi-hou commented
I could have found the problem that `K_stable` was set as `None` instead of the numpy file `K_stable.npy` in default parameters (also for the full_scale MAM). As in our earlier meeting with Sacha, Markus, Hans, and Renan, the interareal probabilistic connectivity was found to generate **Non-existing connectivity** in the connectivity matrix of down-scaled MAM and Renan and I were wondering why. My recent code backtrace found that in down-scaled MAM, the `K_stable` is set as `K_stable.npy`, but in the default_params.py, `K_stable = None`. Thus, thanks to @mlober, this PR should also fix this problem.

2024-01-21 08:59 UTC, albada commented
Why did K_stable = None produce non-existing connectivity? Shouldn't this simply use the connectivity matrix as determined from the anatomical data?

2024-01-22 08:15 UTC, didi-hou commented
> Why did K_stable = None produce non-existing connectivity? Shouldn't this simply use the connectivity matrix as determined from the anatomical data?

What I meant is that: in the current version of MAM, `K_stable` is set as `"K_stable.npy"` in down-scaled MAM, but as `None` in full-scale MAM (default parameters). The connectivity matrix created by down-scaled MAM contains connections that do not appear in the connectivity matrix of full-scale MAM. HEP points out this problem in our earlier meeting. Now I suspect that it's caused by the `K_stable` being set as `None` in full-scale MAM, but `"K_stable.npy"` in down-scaled MAM. But I still need to check and confirm after this PR is merged. Does this make sense?

2024-01-22 09:39 UTC, albada commented
OK, thanks for clarifying.

2024-01-22 09:41 UTC, albada requested changes
All of it looks good to me. I just think the new initial mean membrane potential and the newly introduced structure_reversed require a little bit of documentation describing the reasoning behind these.

2024-01-22 11:04 UTC, mlober commented
> All of it looks good to me. I just think the new initial mean membrane potential and the newly introduced structure_reversed require a little bit of documentation describing the reasoning behind these.

The structure_reversed object was introduced because of an error that occurred when running the analysis saying that this object is missing/not defined. 

The values for the initial membrane potentials were taken from the run_example_fullscale.py script. I have no information on how they were chosen initially. Does anyone know?

2024-01-22 12:22 UTC, albada commented
I would add a comment to the code along the lines of "The initial membrane potential distribution is chosen to be centered on a hyperpolarized state to limit synchronous initial firing, which could bring the model into a high-activity state when the parameters are set according to the metastable condition."

2024-01-24 13:18 UTC, mlober commented on run_example_downscaled.py
> +               'cc_weights_factor': 1.0} # run model in Ground State
Thanks for pointing this out. I will make the changes.

2024-01-24 13:46 UTC, shimoura approved these changes

2024-01-29 10:42 UTC, albada approved these changes

2024-01-29 10:42 UTC, merged